### ISSUE TITLE
The home page link is broken

### ISSUE THREAD

**Issue by pditommaso** [seqan/lambda#105]
The GitHub description contains the following link which does not work. 

http://seqan.de/lambda

![screen shot 2017-07-01 at 12 54 47](https://user-images.githubusercontent.com/816968/27761472-9cdd5442-5e5c-11e7-8273-46a035374f89.png)

**Comment by h-2** [comment]
Thanks for the report! Yes, quite a few things seems to be broken on the seqan-page 😢 
It should just be a redirect to http://seqan.github.io/lambda/ anyway. I have changed it to point there directly now.

**Comment by pditommaso** [comment]
👍
