### ISSUE TITLE
LAMBDA_LONG_PROTEIN_SUBJ_SEQS DB build

### ISSUE THREAD

**Issue by hildebra** [seqan/lambda#115]
Hey, I downloaded the latest lambda (1.9.4) and rebuilt my indexes. However, now I get the problem that all these indexes are not useable: 

LAMBDA - the Local Aligner for Massive Biological DatA
======================================================
Version 1.9.4

Reading index properties...

ERROR: The following exception was thrown while reading the index:
       "Your lambda executable was built with LAMBDA_LONG_PROTEIN_SUBJ_SEQS, but the index was created by an executable that was built without it.You need to recreate the index or rebuild Lambda."
       Make sure the directory exists and is readable; recreate the index and try again.
       If the problem persists, report an issue at https://github.com/seqan/lambda/issues and include this output, as well as the output of `lambda2 --version`, thanks!
system call
/g/bork3/home/hildebra/dev/Perl/reAssemble2Spec//bin/lambda2-1.9.4-Linux-x86_64/bin/./lambda2 searchn -t 24 --percent-identity 75 -n 200 -e 1e-12 --seed-offset 7 --seed-length 14 --seed-delta 1 -b -3 --filter-putative-duplicates on  -q /g/scb/bork/hildebra/Tamoc/GCglobal/GGC13001/ribos/reads_SSU.fna -i /g/bork3/home/hildebra/DB/MarkerG/PR2//gb203_pr2_all_10_28_99p.fasta.lambda -o /MF//GGC13001ITS//LCA/SSUriboRun_bl.0.m8.gz

The index was built using this command:
/g/bork3/home/hildebra/dev/Perl/reAssemble2Spec//bin/lambda2-1.9.4-Linux-x86_64/bin/./lambda2 mkindexn -t 16 -d /g/bork3/home/hildebra/DB/MarkerG/PR2//gb203_pr2_all_10_28_99p.fasta

How can I fix this? I'm not even using a protein DB.
many thanks,
Falk

**Comment by hildebra** [comment]
/g/bork3/home/hildebra/dev/Perl/reAssemble2Spec//bin/lambda2-1.9.4-Linux-x86_64/bin/./lambda2 --version
lambda2 version: 1.9.4
SeqAn version: 2.4.0

**Comment by rrahn** [comment]
Hi the maintainer of the application is currently on vacation, so it may take him a week to get back to your issue.

**Comment by h-2** [comment]
@hildebra Sorry about that, the 1.9.x branch doesn't yet have integration tests, because results still change slightly between runs so that issues wasn't detected. 

I will fix it next week, but if you are impatient, you can just comment out this entire if-clause and rebuild:
https://github.com/seqan/lambda/blob/master/src/search_algo.hpp#L169

**Comment by hildebra** [comment]
Hey, yes would be great to have it working again. Btw, what are the expected performance gains between the ss4 and normal binary, that are in 1.9.3?

**Comment by h-2** [comment]
should be fixed in current master
