### ISSUE TITLE
Floating point exception in mkindexp with small genome file

### ISSUE THREAD

**Issue by f-heeger** [seqan/lambda#118]
When testing a different issue I created the attached fasta file on which mkindexp crashes with the following error:

> Detecting database alphabet... dna5 detected.
> Loading Subject Sequences and Ids... done.
> Dumping Subj Ids... done.
> Dumping untranslated subject lengths... done.
> Translating Subj Sequences... done.
> Dumping unreduced Subj Sequences... done.
> Checking parameters of to-be-built index...done.
> Generating Index 0%  10%  20%  30%  40%  50%  60%  70%  80%  90%  100%
>  Progress:       |....:....:....:....:....:....:....:....:..Floating point exception (core dumped)

My command was:
`lambda2 mkindexp -d trial_lambda_genome.fasta`
May lambda version was the pre-compiled linux binaries of version 1.9.4

[trial_lambda_genome.fasta.txt](https://github.com/seqan/lambda/files/1803013/trial_lambda_genome.fasta.txt)

**Comment by h-2** [comment]
confirmed

**Comment by h-2** [comment]
should be fixed in current master
