### ISSUE TITLE
Database Memory Options

### ISSUE THREAD

**Issue by mbrockman1** [seqan/lambda#120]
Is there a method to maintain the lambda database in memory such that lambda, the program, does not need to load the database into memory each time it is called via the command line? In other words, is there an extension/external program to keep the lambda database in memory and direct the aligner to wherever the database is in memory?

The reasoning behind this is database memory loading is one of the slowest steps, so if we can maintain it in memory, the command line calls would be faster and less computationally intensive.

**Comment by h-2** [comment]
> Is there a method to maintain the lambda database in memory such that lambda, the program, does not need to load the database into memory each time it is called via the command line? In other words, is there an extension/external program to keep the lambda database in memory and direct the aligner to wherever the database is in memory?

> The reasoning behind this is database memory loading is one of the slowest steps, so if we can maintain it in memory, the command line calls would be faster and less computationally intensive.

There is no way through Lambda directly, but if you have enough RAM to maintain two copies of the DB in memory, just copy your database to `/dev/shm` on Linux. This folder is a virtual filesystem that always resides in the RAM. Lambda will still need to load/parse it on every start, but it will be much faster than reading from disk.

A more dedicated client-server model with a background-daemon keeping the database in memory would be possible, but also adds significant complexity and is not trivial to implement...

**Comment by mbrockman1** [comment]
If I place the lambda database in a tmpfs, will lambda, the program, recognize that the database is already in memory, or will it duplicate the database?

**Comment by h-2** [comment]
It will still load/copy the database, but it will be very fast :)

**Comment by h-2** [comment]
Note that you can also build Lambda with support for MMAP via the the flag `LAMBDA_MMAPPED_DB`, see https://github.com/seqan/lambda/wiki/Building-from-source for details on how to build it.

In the past I have noticed performance degradation when doing long searches with many threads (that's why is deactivated by default), but if loading the DB is the bottle-neck, this will very likely help you significantly.

**Comment by h-2** [comment]
LAMBDA_MMAPPED_DB is no longer available, but we will get support for having the database file compressed on-disk, so that should help with loading speeds.
As suggested, the use of /dev/shm will also help.
