### ISSUE TITLE
Building full NT stuck

### ISSUE THREAD

**Issue by bfowle** [seqan/lambda#129]
Hello,

We're attempting to build the full nucleotide database (machine specs = 128 cores, 4TB RAM), which seems to reach this loop: https://github.com/seqan/lambda/blob/master/src/mkindex_saca.hpp#L395 in the process, before reaching 10% on the progress bar, and has been stuck for days+. All CPU cores are maxed out at 100%, `top` shows all threads are in "Running" state, but no signs of life via `strace`. Is there a point where this is never going to budge, or should we just wait longer for this step to complete?

Cheers~

**Comment by bfowle** [comment]
EDIT:
Finally signs of life from `strace` (after many hours of silence...)
Lots of:
```
futex(0xe6aff4, FUTEX_WAIT_PRIVATE, 640, NULL <unfinished ...>`
<... futex resumed> )       = 0
...
munmap(0x7cfa71927000, 281853952 <unfinished ...>
<... munmap resumed> )      = 0
...
<... madvise resumed> )     = 0
madvise(0x7f5448046000, 4096, MADV_DONTNEED) = 0
```
Then back to 100%CPU across all cores.

**Comment by bfowle** [comment]
Closing for now - think it's just going to take many days/maybe even a week.

**Comment by h-2** [comment]
Thanks for your report. The algorithm used for construction by default is well-suited for protein databases, but is particularly bad at dealing with repeats so it might be very slow on nucleotide databases that contain repetitive regions which I assume the NT has many of? 

You can chose a different algorithm that is more tailored to nucleotide sequences by supplying `--algorithm skew7ext`, however this algorithm is not parallelised and provides no progress indication. It might be better in this situation, though... I would recommend taking a smaller sample (maybe 1% of the actual data) and comparing both algorithms to see which is faster – I would also be very much interested in your results on this so I could change default algorithms for nucleotides maybe.

Things to note about the skew algorithm: It  uses excessive amounts of local storage  (up to 30x of the input data size), but is very light in memory usage. If you use it make sure that the temporary directory (the output directory by default) is on local disk and not on network storage (this is a good measure in any case).

**Comment by h-2** [comment]
Another thing is that you seem to be stuck in memory mapping according to the trace. You can try rebuilding lambda without MMAP and see if it improves the performance. Again, I would recommend trying things with a small sample first!

**Comment by bfowle** [comment]
Thanks for the tips~ Here's some preliminary findings regarding building the full NT, which has proved to be a pretty heavy lift, as it includes full genomes up to 99mil+ basepairs for a single sequence. Some "sanitization" was done to the source FASTA file (which was just dumped with `blastdbcmd -entry all ...`) such as trimming the sequence headers to just the first one, etc.

Previously, I attempted building with the `skew7ext` algorithm flag, and stopped it well over a week in, and it only reported about a ~60% completion at that point. I then split the FASTA file up into several ones based on sequence length ("sm" = 6-25,000 bps, "md" = 25,001-5mil bps, "lg" = 5mil+); the sm/md completed relatively quickly (under a day, each); the lg got stuck in the path marked "SECOND STEP" in `mkindex_saca`; it fully deadlocked one time and spent many days not moving past the 5% in another attempt.

This most recent attempt was done with the desire of having it in one single database, so using a much beefier node to accomplish this (128 cores, 4TB RAM, SSDs). First couple attempts I gave it >128 threads (1280, 256) and got "Bus error"s each time (SIGBUS). Also tried this with 1.9.4 and 1.9.5. Finally I got it to run with 1.9.4/default thread count:
- The initial step loaded 2TB of data into memory.
- The "SECOND STEP" 5-10% completed within 2 days and following the code I could see, as it sorts by largest first, the very large sequences took up to a day themselves and the medium/smaller ones took the other day -- using `strace` I could monitor when the mutexes were released, etc. and the interval between these iterations decreased in time. (Curious if modern C++ concurrency/`std::future`s could help here instead of mutexes?)
- The "THIRD STEP" 10%-85% went decently quick at times and (progress indicator would update every 15-40 minutes on average) and very slow on others (3+hours for a single 'tick').
[This is where I am currently waiting, around 50%... I will update this message when this completes.]

(Note, I hadn't attempted a non-mmapped version of the program, I will try that another time/next time.)

Hope this helps shed some light on my experiences, I wish I had more time to dig into the code some more because this is a really helpful, wonderful tool~

**Comment by bfowle** [comment]
UPDATE:
4 days in... it deadlocked
```[pid 31894] 21:21:10 futex(0xe6aff4, FUTEX_WAIT_PRIVATE, 4448, NULL```
Sadness.
Out of curiosity: would compiling it without mmapped be significantly less/more time?
Thanks~

**Comment by h-2** [comment]
> 4 days in... it deadlocked

Hm, that's strange. I have never ever encountered a dead-lock, yet.

> Out of curiosity: would running this without mmap compiled be significantly less/more time?

Version 1.9.5 isn't built with MMAP by default anyway, I am surprised to see you being stuck in MMAP states often. It might be that  SeqAn's fm-index building is caching something to disk internally, but this should only happen at end the end, not during construction of the suffix array which is only sorting.

>  it fully deadlocked one time and spent many days not moving past the 5% in another attempt.

What do you mean by "fully deadlocked"? The progress-bar is not completely smooth. There are some steps that I consider 5% and 10% and then the rest is "dynamic" progress of the suffix array construction. For large databases a halt without seemingly any progress at 5% and 10% can be expected, because it's not possibly to adequately pre-calculate the influence of every step. Also at the end (100%) there might period of no change...

**Comment by bfowle** [comment]
Regarding the deadlocks: I was monitoring `strace` for multiple days with an entry such as `futex(0xe6aff4, FUTEX_WAIT_PRIVATE, 4448, NULL` and no completion after the `NULL` (no newline, no response in `<...>`).

This happened several times in the 5-10% phases with several configurations (mmapped, not mmapped, 1.9.4, 1.9.5), and another at the 85%. On one (less expensive) machine I was running _just_ a set of ~4000 of the largest sequences in the NT (which are full genomes) that were between 5mil-99mil base pairs each; I let run for 3+ days -- the threads that were sleeping eventually got killed by the kernel and were left with one running thread without any further progress. The sequences <5mil base pairs were all able to index within hours, it seems some length above 5mil (not sure the exact minimum) has trouble indexing and gets stuck.

The nodes that were costing us significantly more money to run, I didn't let run longer than a day extra after noticing a deadlock, and that was only ~50% complete when it got stuck -- it was going relatively well between 10%-50% but also went down to all sleeping threads except the main one and that was eventually the only thread left running without any progress change after that.

I believe the first 5% took one day; 5-10% took a little less than a day; 10-50% took another 2 days, and I left it running for another day when it got stuck on 50% and killed it when no extra progress happened in that extra day.

The `skew7ext` version is running right now on our less-expensive node, but that didn't go so well last time I let it run on that machine.

**Comment by h-2** [comment]
I am sorry to hear that things aren't working out as planned. In general a lot more time went in to optimising for proteins I am afraid.

Work is currently underway for lambda3 which will have an entirely new indexing-module and also be more tested on dna databases. Eventually it will also have support for the DREAM framework [1] which allows huge databases and quick updates of those, but I don't yet have an ETA for that.

[1] https://academic.oup.com/bioinformatics/article/34/17/i766/5093228

**Comment by bfowle** [comment]
As a followup--
I let the `skew7ext` algorithm-based one run for about 8 days, it crashed on 45% completion with some pretty inconspicuous `strace` messages... many:
`READING operation could not be completed: "Success"`
and then some general *nix `Bad file descriptor` errors after that.

**Comment by h-2** [comment]
```
READING operation could not be completed: "Success"
```

One of the best error messages from SeqAn2 :see_no_evil: 
IIRC it means that it ran out of disk-space, but I am not 100% sure. Note that  you will never see the disk space actually being used while running the program, because the files that are being written to are already marked as deleted (this trickery ensures they are deleted if the program crashes, but its not very intuitive).

**Comment by h-2** [comment]
Well, I am at loss then. Like, I said, we will hopefully have a working version of lambda3 in the next 2 months which uses different construction algorithms.

Thanks trying the different algorithm options!

**Comment by bfowle** [comment]
UPDATE: I was able to fully build the desired subset of NT on `lambda3`. The original FASTA was 79GB and built into a 136.5GB *.lba. It required up to 1.07TB of RAM at the highest peak, which is quite a bit more RAM requirement than previously in lambda2. (I'm guessing because of how SDSL caches in RAMFS?) I also noticed most of the time it was executing on a single thread, so took quite some time to execute (~28hrs).

After building protein databases with `lambda3` I was able to `searchp` without issue-- the progress bar worked as intended and started gathering results immediately. However, with `searchn`, it took 23+ minutes to just load into memory, then the progress bar jumped immediately to 100%, and sat for hours without finding a single result (on a dataset I know has results on this NT subset) before I stopped it.

**Comment by bfowle** [comment]
Figured I'd share some more findings...
It seems that any sequences that have A,C,G,T only (DNA4) perform the SA sort and index in a reasonable time-frame, whereas DNA5 (any seqs with "N" or other wobble bases...) are completely un-usable.

With the full NT -- around 22mil DNA-only sequences across the tree of life, the SA is sorted within an hour on a 128-core machine with 2TB of RAM.
Testing just Eukaryota with DNA4 and DNA5 -- the SA sort had been stuck between 5% and 10% of the progress bar for a week before I killed it. Doing some `gdb` checks, inspecting registers/memory it did not appear to be even close to being done before killing it.

It seems this problem is no longer an issue -- at least to index -- in `lambda3`, but I found the search functionality still not production-ready, as you've also mentioned clearly in the past.
I suppose for now, it's an unfortunate in-between versions timing, where I can't build the full NT (with DNA5 seqs) with `lambda2`, and also can't use a built `lambda3` index to perform searching properly. :)

**Comment by sarahet** [comment]
Thanks for sharing your test results and observations! We will hopefully solve the issues with the lambda3 nucleotide search in the next few weeks. I will let you know once we figured out the problem(s) and hopefully this will be usable for you soon.
