### ISSUE TITLE
non-amd64 builds are incomplete

### ISSUE THREAD

**Issue by mr-c** [seqan/lambda#163]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953081

>  On amd64, the upstream rules show:
> ```
> [...]
> Install the project...
> /usr/bin/cmake -P cmake_install.cmake
> -- Install configuration: "Release"
> -- Installing: /<<PKGBUILDDIR>>/debian/lambda-align2/usr/libexec/lambda2
> -- Installing: /<<PKGBUILDDIR>>/debian/lambda-align2/usr/libexec/lambda2-sse4
> -- Installing: /<<PKGBUILDDIR>>/debian/lambda-align2/usr/bin/lambda2
> -- Installing: /<<PKGBUILDDIR>>/debian/lambda-align2/usr/share/doc/lambda2/LICEN
> [...]
> ```
> On other architectures e.g. arm64, the build log instead shows:
> ```
> [...]
> /usr/bin/cmake -P cmake_install.cmake
> -- Install configuration: "Release"
> -- Installing: /<<PKGBUILDDIR>>/debian/lambda-align2/usr/share/doc/lambda2/LICENSE.rst
> [...]
```

**Comment by h-2** [comment]
lambda3 will only support amd64.
