### ISSUE TITLE
Version code 1.0.3 compiles as 1.0.2

### ISSUE THREAD

**Issue by sfregoso** [seqan/lambda#165]
Hello,

I need a lambda version 1.0.3 but when I compile it, it says 1.0.2.  Not sure if there is a major difference, but when trying to run the code with a database and query file I get

"Loading Subj Sequences... failed."  but I don't know why it failed.

Any thoughts?

**Comment by h-2** [comment]
Hey, sorry for the long wait.

> I need a lambda version 1.0.3 but when I compile it, it says 1.0.2.

That shouldn't be a problem.

> "Loading Subj Sequences... failed." but I don't know why it failed.

This is usually the case if the file is not readable, e.g. you don't have permissions. Can you double-check that the filename is correct and the file is readable?

You can also run lambda with `-v 2` to increase verbosity of output.

**Comment by h-2** [comment]
Closing this as it is really old. If you have problems with the lambda3 branch, please reopen.
