### ISSUE TITLE
http://ftp.imp.fu-berlin.de/pub/lambda/ does not exists and no databases can be downloaded.

### ISSUE THREAD

**Issue by ghuls** [seqan/lambda#228]
http://ftp.imp.fu-berlin.de/pub/lambda/ does not exists and no databases can be downloaded.

**Comment by h-2** [comment]
We are currently trying to figure out what has happened, and hope to have the files back ASAP.

**Comment by sarahet** [comment]
It should work now. Can you check and confirm this?

**Comment by ghuls** [comment]
Yes. Files seem to be there now. Thanks.
