### ISSUE TITLE
empty database

### ISSUE THREAD

**Issue by f-heeger** [seqan/lambda#54]
If I index an empty *.fasta file (don't ask why) the indexer runs without a problem, but if I start lambda with the index I get an error: 
`Loading Database Index... failed. Did you use the same options as with lambda_indexer?`

Probably the indexer should warn me already or even fail. The lambda error message could also be more helpful.

**Comment by h-2** [comment]
Can you verify that this is fixed in the current master branch? [please make a fresh clone of the repository as some substantial things have changed, also clone with the --depth=2 parameter]

**Comment by f-heeger** [comment]
Yes, correctly gives an error now, when running the indexer on an empty file. [had to use --recursive for cloning because of the switch from subtree to submodule I guess]

**Comment by h-2** [comment]
ok, thanks for checking.

> [had to use --recursive for cloning because of the switch from subtree to submodule I guess]

yep, the documentation will updated shortly.

**Comment by h-2** [comment]
Hm, seems like it doesn't work now when it should, need to re-investigate before release.
