### ISSUE TITLE
Introduce max-values for all numbered parameters (was: Abort Trap: 6 error when parameters are wrong)

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [seqan/lambda#92]
When given the -d option with a wrong file or passing invalid parameters to -nm (I tried 999999999999, but this seems to be too large) lambda simply exists with the error "Abort Trap: 6". I think a more descriptive error message could help understand the issue better.

**Comment by h-2** [comment]
thank you for the report! I will try to reproduce it next week!

**Comment by ewersSaucedo** [comment]
Okay, so I ran into the same error message after I had made my own database. What causes this error? How can I fix it?

Thanks!

**Comment by h-2** [comment]
Thank your for your reports on this. Please tell me first of all which lambda version you are using!
If you are using the stable version (1.0.*), can you also try the development version (1.9.2) and report whether it suffers from the same bug?
I have previously improved the argument checking so it might already be fixed. Please note that you need to recreate the index files when switching to the development version.

**Comment by AlexanderFillbrunn** [comment]
Hi, I tried both lambda-1.9.2-Darwin-x86_64 and lambda-1.0.1-Darwin-x86_64 on macOS 10.12.3. Both had the same problem.

**Comment by AlexanderFillbrunn** [comment]
@ewersSaucedo As I understand it, this problem only occurs if the parameters are not valid anyways. So if you find out which parameter is causing the issues, you should be able to get around this problem. Maybe check the allowed ranges for numeric parameters and the allowed values for others against the values you use.

**Comment by h-2** [comment]
@AlexanderFillbrunn @ewersSaucedo It seems like it might be different issues leading to the same error. Can you post full command lines that you executed and a full log of the program so I can see when/where it crashes?
Thank you!

**Comment by h-2** [comment]
@AlexanderFillbrunn I have just added upper bounds to all parameters: a7e2e71208c741f60aed3b47e017bda3b6c148d1
This will be included in 1.9.3.

@ewersSaucedo If your issue was unrelated to wrong parameters, can you open a new issue with more details? Thank you!
